
[paths]
bios_path = "~/.config/retroarch/system"
roms_path = "~/.config/pystation/roms"
cores_path = "/usr/lib/libretro"

[default_cores]
psx = "mednafen_psx_libretro.so"
gba = "mgba_libretro.so"
nes = "nestopia_libretro.so"
snes = "snes9x_libretro.so"
