
[paths]
bios_folder = "~/.local/share/pystation/bios/"
roms_folder = "~/.local/share/pystation/roms/"
images_folder = "~/.local/share/pystation/screenshots"
cores_path = "/usr/lib/libretro/"

[default_cores]
psx = "play_libretro.so"
gba = "mgba_libretro.so"
nes = "nestopia_libretro.so"
snes = "snes9x_libretro.so"
